spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/parking-control-db?createDatabaseIfNotExist=true
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    open-in-view: false

  flyway:
    locations: classpath:db/migration,classpath:db/testdata